/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity2 */

#ifndef _Included_com_example_androidex_MainActivity2
#define _Included_com_example_androidex_MainActivity2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_MainActivity2
 * Method:    myfunc_open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_myfunc_1open
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity2
 * Method:    myfunc_read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_myfunc_1read
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity2
 * Method:    myfunc_write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_myfunc_1write
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity2
 * Method:    myfunc_close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_myfunc_1close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
